# Change repoURL to the actual remote before applying if different.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openvino-llm-poc
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tusha/openvino-llm-poc.git
    targetRevision: HEAD
    path: k8s/aws
    directory:
      recurse: false
      exclude: argocd-application.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: llm-inference
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
