apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: gateway-api-key
  namespace: llm-inference
spec:
  provider: aws
  parameters:
    region: ap-south-1
    usePodIdentity: "true"
    objects: |
      - objectName: "/openvino-llm-poc/gateway/api-key"
        objectType: "secretsmanager"
        objectAlias: "api-key"
