apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: llm-gateway-internal
  namespace: llm-inference
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    alb.ingress.kubernetes.io/healthcheck-path: /ready
    alb.ingress.kubernetes.io/security-groups: sg-0b68c332fe030f72c
    alb.ingress.kubernetes.io/manage-backend-security-group-rules: "true"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: llm-gateway-service
                port:
                  number: 8080
